# Generated by Django 3.1.1 on 2020-09-28 14:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_otp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otp',
            new_name='Userotp',
        ),
    ]
