# Generated by Django 3.1.1 on 2020-10-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_orderitem_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status_track',
            field=models.IntegerField(default=0),
        ),
    ]
