# Generated by Django 3.1.1 on 2020-09-17 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200917_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.product'),
        ),
    ]
