# Generated by Django 3.1.1 on 2020-09-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_wishlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
