# Generated by Django 3.1.1 on 2020-09-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_wishlist_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='example', max_length=300),
            preserve_default=False,
        ),
    ]
