# Generated by Django 3.1.1 on 2020-09-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
